name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Python (doesn’t matter if 3.13, since no deps are installed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Build the package
      - name: Build package
        run: poetry build

      # Publish to PyPI
      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PANDALYZE_PYPI_SECRET }}
