name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Sanity check
      - run: python --version

      # Install Poetry (pin version for reproducibility)
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.1.4
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Check Poetry version
      - run: poetry --version

      # Build the package
      - name: Build package
        run: poetry build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PANDALYZE_PYPI_SECRET }}
        run: poetry publish --no-interaction --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
